spring.application.name=tasks
server.port=8081

# Connection URL format
spring.datasource.url=jdbc:postgresql://database-2.c2xaiagi4mxa.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

aws.region=us-east-1
aws.sqs.queue-url=https://sqs.us-east-1.amazonaws.com/993952121406/demo-sqs